accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        views.UserLogin.as_view(),
        name='login'
    ),
     path(
        'logout/',
        views.UserLogout.as_view(),
        name='logout'
    ),
]

work/urls.py
from django.urls import path
from . import views

app_name = 'work'

urlpatterns = [
    path(
        'companies/',
        views.CompList.as_view(),
        name='comp_list'
    ),
    path(
        'companies/<int:pk>/',
        views.CompDetail.as_view(),
        name='comp_detail'
    ),
    path(
        'companies/<int:pk>/managers/',
        views.ManagList.as_view(),
        name='manag_list'
    ),
    path(
        'workers/',
        views.WorkerList.as_view(),
        name='worker_list'
    ),
    path(
        'workers/<int:pk>/',
        views.WorkerDetail.as_view(),
        name='worker_detail'
    ),
    path(
        'create_work/',
        views.CreateWork.as_view(),
        name='create_work'
    ),
    path(
        'hire',
        views.Hire.as_view(),
        name='hire'
    ),
    path(
        'workplace/<int:pk>/',
        views.update_wp,
        name='update_wp'
    ),
]

work_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('work.urls', namespace='work')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

work/models.py
from django.db import models
from django.utils import timezone


NEW = 0
APPROVED = 1
CANCELLED = 2
FINISHED = 3


class Company(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'company {self.name}'


class Manager(models.Model):
    company = models.ForeignKey(
        Company, related_name='managers', on_delete=models.CASCADE)

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=128)

    def __str__(self):
        return f'manager {self.first_name} {self.last_name} at {self.company}'


class Work(models.Model):
    company = models.ForeignKey(
        Company, related_name='works', on_delete=models.CASCADE)

    name = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'work {self.name} at {self.company.name} company'

    class Meta:
        unique_together = ['company', 'name']
        permissions = (
            ('can_create_work', 'Can create new work'),
        )


class Worker(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self):
        return f'worker {self.first_name} {self.last_name}'


class WorkPlace(models.Model):

    manager = models.ForeignKey(
        Manager, related_name='workplaces', on_delete=models.CASCADE)

    STATUS_CHOICES = (
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        (FINISHED, 'Finished'),
    )

    status = models.IntegerField(choices=STATUS_CHOICES, default=NEW)

    work = models.ForeignKey(
        Work, related_name='workplaces', on_delete=models.CASCADE)

    worker = models.ForeignKey(
        Worker, related_name='workplaces', on_delete=models.CASCADE)

    week_limit = models.IntegerField(default=40)

    def __str__(self):
        return (
            f'workplace {self.work.name} at {self.work.company.name} company')

    class Meta:
        unique_together = ['work', 'worker']
        ordering = ['status']
        permissions = (
            ('can_hire', 'Can hire workers'),
        )


class WorkTime(models.Model):

    date = models.DateField()

    time_start = models.TimeField()
    time_end = models.TimeField()

    worker = models.ForeignKey(
        Worker, on_delete=models.CASCADE)

    workplace = models.ForeignKey(
        WorkPlace, related_name='worktimes', on_delete=models.CASCADE)

    STATUS_CHOICES = (
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=NEW)


class Statistics(models.Model):

    created_date = models.DateField(auto_now_add=True)

    workplace = models.ForeignKey(
        WorkPlace, related_name='workplaces', on_delete=models.CASCADE)

    worker = models.ForeignKey(
        Worker, related_name='workers', on_delete=models.CASCADE)

    total_worked_time = models.FloatField()

work/forms.py
from django import forms
from .models import WorkTime, WorkPlace


class CreateWorkTime(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        time_start = cleaned_data.get('time_start')
        time_end = cleaned_data.get('time_end')

        if time_start and time_end:
            if time_start >= time_end:
                raise forms.ValidationError('Incorrect time values.')

    class Meta:
        model = WorkTime
        fields = ('date', 'time_start', 'time_end')


class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = WorkPlace
        fields = []


class CreateWorkPlace(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        manager = cleaned_data.get('manager')
        work = cleaned_data.get('work')

        if manager.company != work.company:
            raise forms.ValidationError('Should belong to the same company.')

    class Meta:
        model = WorkPlace
        fields = ['manager', 'work', 'worker', 'week_limit']

work/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import (
    Company, Work, Worker, WorkTime, WorkPlace,
    NEW, APPROVED, CANCELLED, FINISHED)
from .forms import (
        CreateWorkTime, ChangeStatusForm,
        CreateWorkPlace)
from django.views.generic import (
    View, ListView, DetailView, CreateView, FormView)
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import (
    PermissionRequiredMixin, LoginRequiredMixin)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import logging
import datetime

logger = logging.getLogger('my_log')
logger.setLevel(logging.INFO)


class CompList(ListView):

    """Implementing a view to display companies list"""

    model = Company
    template_name = 'work/comp_list.html'
    context_object_name = 'companies'


class CompDetail(DetailView):

    """Implementing a view to display company detail page"""

    model = Company
    template_name = 'work/comp_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['works'] = self.get_object().works.all()
        context['no_approved_wp'] = self.get_object().works.exclude(
                                                    workplaces__status=1)
        return context


class ManagList(DetailView):

    """Implementing a view to display manager's list"""

    model = Company
    template_name = 'work/manag_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['managers'] = self.get_object().managers.all()
        return context


class WorkerList(ListView):

    """Implementing a view to display worker's list"""

    model = Worker
    template_name = 'work/worker_list.html'
    context_object_name = 'workers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['no_approved_wp'] = Worker.objects.exclude(
                                    workplaces__status=1)
        return context


class WorkerDisplay(DetailView):

    """Implementing a view to display worker's info"""

    model = Worker

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workplaces'] = self.get_object().workplaces.all()
        context['form'] = CreateWorkTime()
        if APPROVED in self.get_object().workplaces.values_list(
                                        'status', flat=True):
            context['working_now'] = True
        return context


class WorkerWT(SingleObjectMixin, FormView):

    """Implementing a view for creating worktimes"""

    template_name = 'work/worker_detail.html'
    form_class = CreateWorkTime
    model = WorkTime

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            current_worker = Worker.objects.get(pk=kwargs['pk'])

            date_str = form.data.get('date')
            date = datetime.datetime.strptime(date_str, "%m/%d/%Y").date()

            last_wt = None

            if current_worker.workplaces.exists():
                last_wp = current_worker.workplaces.latest('id')
                if last_wp.worktimes.exists():
                    last_wt = last_wp.worktimes.latest('id')

            if last_wt and last_wt.date >= date:
                form.add_error('date', 'Incorrect date value.')
            else:
                wt = form.save(commit=False)
                wt.worker = current_worker
                wt.workplace = current_worker.workplaces.get(
                                        status=APPROVED)
                wt.save()
                return redirect('work:worker_detail', kwargs['pk'])

        logger.info('Form is invalid')  # pragma: no cover

        return render(request, self.template_name, {
                'worker': Worker.objects.get(pk=kwargs['pk']),
                'workplaces': Worker.objects.get(
                            pk=kwargs['pk']).workplaces.all(),
                'working_now': True,
                'form': form
            })


class WorkerDetail(LoginRequiredMixin, View):

    """Implementing a view for worker's detail page"""
 
    def get(self, request, *args, **kwargs):
        view = WorkerDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = WorkerWT.as_view()
        return view(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class CreateWork(PermissionRequiredMixin, CreateView):

    """Implementing a view for creating work"""

    permission_required = 'work.can_create_work'
    raise_exception = True

    model = Work
    fields = ['company', 'name']
    template_name = 'work/create_work.html'
    success_url = '/companies/'


@method_decorator(login_required, name='dispatch')
class Hire(PermissionRequiredMixin, CreateView):

    """Implementing a view for hiring workers"""

    permission_required = 'work.can_hire'
    raise_exception = True

    form_class = CreateWorkPlace
    template_name = 'work/hire.html'

    def get_success_url(self, **kwargs):
        return reverse(
            'work:worker_detail', kwargs={'pk': self.object.worker.id})


def update_wp(request, pk):

    """Implementing a view for changing WorkPlace status"""

    wp = get_object_or_404(WorkPlace, pk=pk)

    if request.method == "POST":
        form = ChangeStatusForm(request.POST, instance=wp)

        wp = form.save(commit=False)

        if 'approve_btn' in form.data:

            if WorkPlace.objects.filter(
                        worker=wp.worker).filter(status=APPROVED).exists():
                prev_wp = WorkPlace.objects.filter(
                        worker=wp.worker).get(status=APPROVED)
                prev_wp.status = FINISHED
                prev_wp.save()

            wp.status = APPROVED

            if WorkPlace.objects.filter(
                        worker=wp.worker).filter(status=NEW).exists():
                all_new_wp = WorkPlace.objects.filter(
                            worker=wp.worker).filter(status=NEW)
                for new_wp in all_new_wp:
                    new_wp.status = CANCELLED
                    new_wp.save()

        elif 'cancel_btn' in form.data:
            wp.status = CANCELLED

        wp.save()
        return redirect('work:worker_detail', pk=wp.worker.id)

work/templates/work/base.html
{% load i18n %}
{% load static %}

<html>
    <head>
        <title>WorkManagment</title>
        <link rel="stylesheet" type="text/css" href="{% static 'work/style.css' %}">
    </head>
    <body>
        <div class='container'>
            <header>
                {% if user.is_authenticated %}
                    <div class='log'><a href="{% url 'accounts:logout' %}">{% trans "LogOut" %}</a></div>
                {% else %}
                    <div class='log'><a href="{% url 'accounts:login' %}">{% trans "LogIn" %}</a></div>
                {% endif %}
                <nav class='menu'>
                    <a href="{% url 'work:comp_list' %}">{% trans "Companies" %}</a>
                    <a href="{% url 'work:worker_list' %}">{% trans "Workers" %}</a>
                    <a href="{% url 'work:create_work' %}">{% trans "New" %}</a>
                    <a href="{% url 'work:hire' %}">{% trans "Hire" %}</a>
                </nav>
            </header>
            <hr><br>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

work/templates/work/comp_detail.html
{% extends 'work/base.html' %}

{% block content %}
    <h1 class='company'>{{ company.name }}</h1>
    <p><a href="{% url 'work:manag_list' company.id %}">Managers</a></p>
    <ul>
    {% for work in works %}
        <div class='work'>
            <li>{{ work.name }}
                {% if work in no_approved_wp %}
                    <p class='position'>No approved workplaces.</p>
                {% else %}
                    <ul class='position'>
                    {% for wp in work.workplaces.all %}
                        {% if wp.status == 1 %}
                            <li>{{ wp.worker.first_name }} {{ wp.worker.last_name }}</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                {% endif %}
            </li>
        </div>
    {% endfor %}
    </ul>
{% endblock %}

work/templates/work/comp_list.html
{% extends 'work/base.html' %}

{% block content %}
    {% if companies %}
        <ul>
        {% for company in companies %}
            <li class='company'><a href="{% url 'work:comp_detail' company.id %}">{{ company.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p class='work'>No companies.</p>
    {% endif %}
{% endblock %}

work/templates/work/create_work.html
{% extends 'work/base.html' %}

{% block content %}
    <form method="post" class='adding_form'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" />
    </form>
{% endblock %}

work/templates/work/hire.html
{% extends 'work/base.html' %}

{% block content %}
    <form method="post" class='adding_form'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" />
    </form>
{% endblock %}

work/templates/work/manag_list.html
{% extends 'work/base.html' %}

{% block content %}
    <h1 class='company'><a href="{% url 'work:comp_detail' company.id %}">{{ company.name }}</a></h1>
    {% if managers %}
        <ul>
        {% for manager in managers %}
            <li class='work'>{{ manager.first_name }} {{ manager.last_name }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p class='work'>No managers.</p>
    {% endif %}
{% endblock %}

work/templates/work/worker_detail.html
{% extends 'work/base.html' %}

{% block content %}
    <h1 class='company'>{{ worker.first_name }} {{ worker.last_name }}</h1>
    {% if workplaces %}
        <ul>
        {% for wp in workplaces %}
            <div class='work'>
            {% if wp.status != 2 %}
                <li>{{ wp.work.name }} at {{ wp.work.company.name }} ({{ wp.get_status_display }})
                    {% if not wp.status %}
                        <form action="{% url 'work:update_wp' wp.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class='status' value="Approve" name='approve_btn'/>
                            <input type="submit" class='status' value="Cancel" name='cancel_btn'/>
                        </form>
                    {% endif %}
                    <ul>
                    {% for wt in wp.worktimes.all %}
                        <li class='position'>
                            <p>Date: {{ wt.date|date:"d.m.Y" }}</p>
                             {{ wt.time_start|time:"H:i" }} – {{ wt.time_end|time:"H:i" }}
                        </li>
                    {% endfor %}
                    </ul>
                </li>
            {% endif %}
            </div>
        {% endfor %}
        </ul>
    {% endif %}
    {% if working_now %}
        <form method="post" class='adding_form'>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add" />
        </form>
    {% else %}
        <p class='work'>Not working now.</p>
    {% endif %}
{% endblock %}

work/templates/work/worker_list.html
{% extends 'work/base.html' %}

{% block content %}
    {% if workers %}
        <ul>
        {% for worker in workers %}
            <div class='work'>
                <li>
                    <a href="{% url 'work:worker_detail' worker.id %}">{{ worker.first_name }} {{ worker.last_name }}</a>
                    {% if worker in no_approved_wp %}
                        <p class='position'>Not working now.</p>
                    {% endif %}
                    {% for wp in worker.workplaces.all %}
                        {% if wp.status == 1 %}
                            <p class='position'>{{ wp.work.name }} at {{ wp.work.company.name }}</p>
                        {% endif %}
                    {% endfor %}
                </li>
            </div>
        {% endfor %}
        </ul>
    {% else %}
        <p class='work'>No workers.</p>
    {% endif %}
{% endblock %}